function loginUser(event) {
    event.preventDefault();

    const email = document.getElementById("email").value;
    const password = document.getElementById("password").value;

    // Demo login credentials
    if (email === "admin@gmail.com" && password === "123456") {
        alert("Login Successful!");

        // Open Home Page
        window.location.href = "index.html";
    } else {
        alert("Invalid Email or Password!");
    }

    return false;
}